### ISSUE TITLE
Maps keep centering while scrolling

### ISSUE THREAD

**Issue by jowieme** [lab9k/Parking#7] opened 2017-09-18 08:11 UTC

**Comment by tolauwae** [comment] 2017-09-18 08:19
Can't replicate the problem in my local build. This seems to be a problem unique to the server.

**Comment by tolauwae** [comment] 2017-09-19 12:48
Closing this issue as we've moved the project to our github page and the problem isn't manifesting there.

**Closed as completed** 2017-09-19 12:48 UTC
Labels: bug
